### ISSUE TITLE
📖 USER STORY: Header and Footer

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/elevate-hackathon-2024#16]
### User Story

As a **user**, I can **be presented with a consistent header and footer on the site** so that I can **easily navigate the site**.

### Acceptance Criteria

- Header and footer are consistent on all pages
- User can navigate to different pages using links

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Install Flowbite via CDN by adding to `base.html`
- [x] Add and style header and footer
- [x] Check links navigate to pages correctly

**Comment by Dee-McG** [comment]
CV templates header link not yet complete

**Comment by Dee-McG** [comment]
Legal link in footer doesn't work
