### ISSUE TITLE
📖 USER STORY: Sign In

### ISSUE THREAD

**Issue by Dee-McG** [stephendawsondev/elevate-hackathon-2024#2]
### If applicable, add a related Epic.

Epic: <Link epic if applicable>

### User Story

As a user, I want to be able to sign in, so that I can see my personal CV's and stats

### Acceptance Criteria

- User can successfully sign in

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Sign In Page Styled
- [x] Tested on deployed version

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [ ]

**Comment by stephendawsondev** [comment]
Tested on deployed version
