### ISSUE TITLE
📖 USER STORY: Record Skills

### ISSUE THREAD

**Issue by Dee-McG** [stephendawsondev/elevate-hackathon-2024#9]
### User Story

As a user, I want to add my skills to my CV template so they appear on the appropriate section

### Acceptance Criteria

- User can add their skills to their CV template

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Add skills form to the Create CV page
- [x] Create model for skills with a Foreign Key to the CV_ID and User, additional skills field (String, CSV)
- [x] Form styled

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [ ]

**Comment by stephendawsondev** [comment]
@ShaneByrne0963 Is this one okay to close?
